# name: 'Build Docker Image'

# on:
#   push:
#     branches:
#       - master  # Trigger on push to the master branch

# permissions:
#   contents: read

# jobs:
#   build:
#     name: 'Docker Image'
#     runs-on: ubuntu-latest

#     steps:
#     # Step 1: Checkout the repository
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     # Step 2: Set up GCP Authentication using the service account key
#     - name: Set up GCP authentication
#       id: auth
#       uses: 'google-github-actions/auth@v2'
#       with: 
#         credentials_json: '${{ secrets.GCP_KEY }}'  # Ensure GCP_KEY is set in your repository secrets

#     # Step 3: Docker Authentication
#     - name: Docker Authentication
#       run: | 
#         gcloud auth configure-docker us-west1-docker.pkg.dev

#     # Step 4: Build and Push Docker Image
#     - name: Build image
#       run: docker build . --tag us-west1-docker.pkg.dev/mythic-delight-434312-r1/hu-devops/

#     - name: Push image
#       run: docker push us-west1-docker.pkg.dev/mythic-delight-434312-r1/hu-devops/







name: Docker build and push to Artifact Registry

on:
  push:
    branches:
      - master
      - github-action

env:
  PROJECT_ID: mythic-delight-434312-r1
  GAR_LOCATION: us-west1
  REPOSITORY: hu-devops
  IMAGE: main

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Docker build'
      run: |-
        docker build --t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" ./
          
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
        token_format: 'access_token'

    # - uses: 'docker/login-action@v1'
    #   name: 'Docker login'
    #   with:
    #     registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
    #     username: 'oauth2accesstoken'
    #     password: '${{ steps.auth.outputs.access_token }}'
    #     # Step 3: Docker Authentication
    - name: Docker Authentication
      run: | 
        gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: 'Docker push'
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
