name: 'Build Docker Image'

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
permissions:
  contents: read

jobs:
  build:
    name: 'Docker Image'
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up GCP Authentication using the service account key
    - name: Set up GCP authentication
      id: auth
      uses: 'google-github-actions/auth@v2'
      with: 
        credentials_json: '${{ secrets.GCP_KEY }}'  # Ensure GCP_KEY is set in your repository secrets

    # Step 3: Docker Authentication
    - name: Docker Authentication
      run: | 
        gcloud auth configure-docker us-west1-docker.pkg.dev

    # # Step 4: Build the Docker image  
    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t us-west1-docker.pkg.dev/mythic-delight-434312-r1/hu-devops:latest ./
    #     docker push us-west1-docker.pkg.dev/mythic-delight-434312-r1/hu-devops:latest
    # - name: List Docker Images
    #   run: |
    #     docker images

    # Step 5: Push to GCR
    steps:
      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
       #   gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: mythic-delight-434312-r1
          image_name: server-end
          image_tag: latest,v1
          dockerfile: ./Dockerfile