name: 'Terraform with GCP Authentication'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Set up the GCP authentication using the service account key stored in GitHub Secrets
    - name: Set up GCP authentication
      id: 'auth'
      run: |
        echo "${{ secrets.GCP_KEY }}" > "${HOME}/gcp-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
        gcloud config set project "mythic-delight-434312-r1"

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Generate a Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false

    # Apply the Terraform Plan on push to master
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
