name: 'Terraform with GCP'

# on:
#   push:
#     branches:
#       - master  # Trigger on push to the master branch
  workflow_dispatch:  # Manual trigger

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up GCP Authentication using the service account key
    - name: Set up GCP authentication
      id: auth
      uses: 'google-github-actions/auth@v2'
      with: 
        credentials_json: '${{ secrets.GCP_KEY }}'  # Ensure GCP_KEY is set in your repository secrets

    # Step 3: Install Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6  # You can specify the version you need, or leave it out to use the latest

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: terraform  # Specify your working directory

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
      working-directory: terraform  # Specify your working directory

    # Step 6: Terraform Apply (only when manually triggered)
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false tfplan  # Specify the tfplan file
      working-directory: terraform  # Specify your working directory
